# Generated by Django 4.2.9 on 2024-02-04 06:59

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_tags_recipeingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=7, samples=None, unique=True, verbose_name='Цвет тега HEX'),
        ),
    ]
