# Generated by Django 4.2.9 on 2024-02-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_follow_unique_user_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooduser',
            name='is_subcribed',
            field=models.BooleanField(default=False),
        ),
    ]
