# Generated by Django 4.2.9 on 2024-02-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_fooduser_is_subcribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooduser',
            old_name='is_subcribed',
            new_name='is_subscribed',
        ),
    ]
