# Generated by Django 4.2.9 on 2024-02-06 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_is_subcribed_fooduser_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooduser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username может содержать только буквы, цифры и  @/./+/-/_..', regex='^[\\w.@+-]+$')], verbose_name='Имя пользователя'),
        ),
    ]
