# Generated by Django 4.2.9 on 2024-02-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_fooduser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('user',), 'verbose_name': 'подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='fooduser',
            options={'ordering': ('username',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
