# Generated by Django 4.2.9 on 2024-02-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_follow_options_alter_fooduser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('user', 'following'), 'verbose_name': 'подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RemoveField(
            model_name='fooduser',
            name='is_subscribed',
        ),
    ]
