# Generated by Django 4.2.9 on 2024-02-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_fooduser_is_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooduser',
            name='is_subscribed',
        ),
    ]
